export const CARD_BG = [
    { id : 1 , bgcolor : "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)"},
    { id : 2 , bgcolor : "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)"},
    { id : 3 , bgcolor : "linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)"},
    { id : 4 , bgcolor : "linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)"},
    { id : 5 , bgcolor : "linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)"},
    { id : 6 , bgcolor : "linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)"},
    { id : 7 , bgcolor : "linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)"},
    { id : 8 , bgcolor : "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)"},
    { id : 9 , bgcolor : "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)"},
    { id : 10 ,bgcolor : "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)"},
]


export const APP_FEATURES = [
    {
        id: "01",
        title: "AI-Powered Question Generation",
        description:
            "Get role-specific interview questions and answers generated by AI based on your role, experience, and focus topics."
    },
    {
        id: "02",
        title: "Deep Concept Explanations",
        description:
            "Click 'Learn More' on any question to get AI-generated explanations with code examples for better understanding."
    },
    {
        id: "03",
        title: "Organized Session Management",
        description:
            "Create multiple interview prep sessions for different roles. Each session stores your questions, progress, and notes."
    },
    {
        id: "04",
        title: "Smart Question Pinning",
        description:
            "Pin important questions to keep them at the top. Perfect for marking tricky topics you want to review frequently."
    },
    {
        id: "05",
        title: "Expandable Question Library",
        description:
            "Load more AI-generated questions anytime within a session. Continuously expand your practice set as you progress."
    }
];